version: '3.1'
services:
  db:
    build: ./db-tier  # Build from the Dockerfile in db-tier
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: office_db
    ports:
      - "3306:3306"

