version: '3.1'

services:
  db:
    image: dineshkundo/db-tier:1.0  # Use the pushed Docker Hub image
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: office_db
    ports:
      - "3306:3306"

  web-tier:
    image: dineshkundo/web-tier:1.0  # Use the pushed Docker Hub image
    ports:
      - "8080:8080"

  app-tier:
    image: dineshkundo/app-tier:1.0  # Use the pushed Docker Hub image
    ports:
      - "8081:8081"
    depends_on:
      - db
